wake_up = float(input("enter time of waking up:"))
breakfast = float(input("enter time of breakfast:"))
study = float(input("enter no of hours studied :"))
lunch = float(input("enter time of lunch :"))
exercise = float(input("enter no of hours of exercise:"))
dinner = float(input("enter time of dinner:"))
total_hours_studied = study + exercise
# ("pull terminal up while seeing results to see the output clearly")
print("\nDaily Routine")
print("\nWake up -", wake_up, "AM")
print("\nBreakfast -", breakfast, "AM")
print("\nStudy -", study, "hours")
print("\nLunch -", lunch, "PM")
print("\nExercise -", exercise, "hours")
print("\nDinner -", dinner, "PM")
print("Total hours studied:", total_hours_studied)